import Pagination from '../components/Pagination';
import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Search,Download,Trash2,ChevronLeft,ChevronRight,Eye,X,Upload,FileSpreadsheet,CheckCircle2,Columns3,Pencil,Save} from 'lucide-react';
import {api,download} from '../api';
import {useAuth} from '../App';
import {getDateRange,rangeOptions} from '../dateRanges';
import {formatInterviewTime, interviewTimeSeconds} from '../time';
import {interviewChanges} from '../utils/interviewEdits';

const technologies=['SQL Support / Developer','AWS / DevOps','Testing','Power BI / Tableau / Data Analytics','Data Science','Python Developer','AR Caller','Medical Coding / Billing','DV360','OSI Soft PI','Full Stack Developer','AI Engineer','Java Developer','.NET Developer','Other'];
const statuses=['Scheduled','In Progress','Selected','Placed','Rejected','On Hold'];
const exportFields=[['candidateName','Candidate name'],['candidateEmail','Candidate email'],['candidateMobile','Candidate mobile'],['interviewDate','Interview date'],['interviewTime','Interview time'],['technology','Technology'],['companyName','Company name'],['hrName','HR name'],['hrEmail','HR email'],['hrMobile','HR mobile'],['interviewRound','Interview round'],['status','Status'],['selectedCompany','Selected company'],['remarks','Remarks'],['submittedBy','Submitted by']];
const todayISO=()=>{const date=new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,10)};
const mobileOnly=value=>value.replace(/\D/g,'').slice(0,10);
const nameOnly=value=>value.replace(/[^A-Za-z\s]/g,'');

export default function Interviews(){
  const {user}=useAuth(),fileRef=useRef(),[items,setItems]=useState([]),[selected,setSelected]=useState(null),[editSelected,setEditSelected]=useState(false),[showExport,setShowExport]=useState(false),[meta,setMeta]=useState({page:1,pages:1,total:0});
  const [filters,setFilters]=useState(()=>({search:'',status:'',technology:'',...getDateRange('today'),page:1,limit:10})),[quickRange,setQuickRange]=useState('today'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[importing,setImporting]=useState(false);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t)},[notice]);
  const qs=()=>new URLSearchParams(Object.entries(filters).filter(([,value])=>value)).toString();
  const requestRef=useRef(null);
  function load(){
    requestRef.current?.abort();
    const controller=new AbortController();requestRef.current=controller;
    setLoading(true);setError('');
    api('/interviews?'+qs()+'&includeSheet=true',{signal:controller.signal})
      .then(result=>{if(!controller.signal.aborted){setItems(result.items);setMeta(result)}})
      .catch(e=>{if(!controller.signal.aborted)setError(e.message)})
      .finally(()=>{if(!controller.signal.aborted)setLoading(false)});
  }
  useEffect(()=>{requestRef.current?.abort();setLoading(true);const timer=setTimeout(load,filters.search?250:0);return()=>{clearTimeout(timer);requestRef.current?.abort()}},[JSON.stringify(filters)]);
  async function remove(id){if(String(id).startsWith('sheet-'))return setError('Delete Google Form responses in the linked Google Sheet.');if(!confirm('Delete this interview permanently?'))return;await api('/interviews/'+id,{method:'DELETE'});load()}
  async function importSheet(event){const file=event.target.files[0];if(!file)return;setImporting(true);setError('');setNotice('');try{const form=new FormData();form.append('file',file);const result=await api('/interviews/import',{method:'POST',body:form});setNotice(`${result.imported} records imported${result.failed?`; ${result.failed} rows failed validation`:''}.`);load()}catch(e){setError(e.message)}finally{setImporting(false);event.target.value=''}}
  async function setPlaced(item,placed){try{await api(`/interviews/${item._id}/placement`,{method:'PATCH',body:JSON.stringify({placed})});setSelected(null);load()}catch(e){setError(e.message)}}
  function applyRange(key){setQuickRange(key);setFilters(current=>({...current,...getDateRange(key),page:1}))}

  return <section className="panel tablepanel glossy">
    <div className="pagehead"><div><span className="eyebrow">INTERVIEW PIPELINE</span><h1>Interview schedules</h1><p>{meta.total} records in your workspace</p></div><div className="headbuttons">
      {user.role==='admin'&&<><input ref={fileRef} hidden type="file" accept=".xlsx,.xls,.csv" onChange={importSheet}/><button className="secondary" disabled={importing} onClick={()=>fileRef.current.click()}><Upload size={17}/>{importing?'Importing…':'Import Excel'}</button><button className="ghostbtn" onClick={()=>download('/interviews/import-template','interview-import-template.xlsx')}><FileSpreadsheet size={17}/> Template</button></>}
      {user.role!=='user'&&(user.role!=='staff'||user.permissions?.exportInterviews!==false)&&<button className="primary" onClick={()=>setShowExport(true)}><Download size={17}/> Export Excel</button>}
    </div></div>
    {error&&<div className="alert">{error}</div>}{notice&&<div className="success-alert"><CheckCircle2 size={17}/>{notice}<button type="button" className="notice-close" aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={16}/></button></div>}
    <div className="quickranges"><span>Show:</span>{rangeOptions.map(([key,label])=><button key={key} className={quickRange===key?'active':''} onClick={()=>applyRange(key)}>{label}</button>)}</div>
    <div className="filters"><label className="search"><Search/><input placeholder="Search candidate, email, company…" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value,page:1})}/></label><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value,page:1})}><option value="">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><select value={filters.technology} onChange={e=>setFilters({...filters,technology:e.target.value,page:1})}><option value="">All technologies</option>{technologies.map(x=><option key={x}>{x}</option>)}</select><label className="datefilter"><span>From</span><input type="date" value={filters.from} onChange={e=>{setQuickRange('custom');setFilters({...filters,from:e.target.value,page:1})}}/></label><label className="datefilter"><span>To</span><input type="date" value={filters.to} onChange={e=>{setQuickRange('custom');setFilters({...filters,to:e.target.value,page:1})}}/></label></div>
    <div className="tablewrap"><table className="interviewtable"><thead><tr><th>Candidate</th><th>Interview</th><th>Technology</th><th>Company</th><th>HR contact</th><th>Support staff</th><th>Round</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan="9" className="empty">Loading interviews…</td></tr>:items.length?items.map(item=><tr key={item._id}><td><div className="person"><span>{item.candidateName.slice(0,2).toUpperCase()}</span><div><strong>{item.candidateName}</strong><small>{item.candidateEmail}</small><small>{item.candidateMobile}</small></div></div></td><td><strong>{new Date(item.interviewDate).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</strong><small className="block">{formatInterviewTime(item.interviewTime)}</small></td><td>{item.technology}</td><td><strong>{item.companyName}</strong></td><td><strong>{item.hrName}</strong><a className="contactlink" href={`mailto:${item.hrEmail}`}>{item.hrEmail}</a><a className="contactlink" href={`tel:${item.hrMobile}`}>{item.hrMobile}</a></td><td><div className="assigned-names">{item.assignedStaff?.length?item.assignedStaff.map(person=><span key={person._id}>{person.name}</span>):<em>Unassigned</em>}</div></td><td>{item.rounds?.[0]||'—'}</td><td><span className={`status ${item.status.toLowerCase().replace(' ','-')}`}>{item.status}</span></td><td className="actions"><button title="View all details" className="iconbtn" onClick={()=>{setEditSelected(false);setSelected(item)}}><Eye size={17}/></button>{user.role==='user'&&item.status==='Selected'&&<button className="placedbtn" onClick={()=>setPlaced(item,true)}>Mark placed</button>}{user.role==='admin'&&<button title="Edit record" className="iconbtn" onClick={()=>{setEditSelected(true);setSelected(item)}}><Pencil size={17}/></button>}{user.role==='admin'&&item.source!=='google-sheet'&&<button title="Delete" className="iconbtn danger" onClick={()=>remove(item._id)}><Trash2 size={16}/></button>}</td></tr>):<tr><td colSpan="9" className="empty">No interviews match these filters.</td></tr>}</tbody></table></div>
    <Pagination page={meta.page} pages={meta.pages} total={meta.total} limit={filters.limit} loading={loading} setPage={page=>setFilters(current=>({...current,page}))} setLimit={limit=>setFilters(current=>({...current,limit,page:1}))}/>
    {selected&&<Details item={selected} initialEditing={editSelected} user={user} close={()=>setSelected(null)} refreshed={load} saved={()=>{setSelected(null);setNotice('Interview details updated successfully.');load()}}/>} 
    {showExport&&<ExportDialog filters={qs()} close={()=>setShowExport(false)}/>} 
  </section>
}

function ExportDialog({filters,close}){
  const all=exportFields.map(([key])=>key),hrPreset=['companyName','hrName','hrEmail','hrMobile'];
  const [fields,setFields]=useState(all),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const toggle=key=>setFields(current=>current.includes(key)?current.filter(x=>x!==key):[...current,key]);
  async function run(){if(!fields.length){setError('Select at least one column to export.');return}setBusy(true);setError('');try{const params=new URLSearchParams(filters);params.set('fields',fields.join(','));await download('/interviews/export?'+params.toString(),'interviews.xlsx');close()}catch(e){setError(e.message)}finally{setBusy(false)}}
  return createPortal(<div className="modalback"><div className="modal exportmodal dialog-shell"><div className="dialog-header"><button className="modalclose" onClick={close}><X/></button><div className="exporticon"><Columns3/></div><div><span className="eyebrow">CUSTOM EXCEL EXPORT</span><h2>Choose columns</h2><p>Select only the information you need. Current filters will also be applied.</p></div></div><div className="dialog-body"><div className="exportpresets"><button type="button" onClick={()=>setFields(all)}>Select all</button><button type="button" onClick={()=>setFields(hrPreset)}>Company & HR only</button><button type="button" onClick={()=>setFields([])}>Clear all</button></div><div className="exportgrid">{exportFields.map(([key,label])=><label className={fields.includes(key)?'selected':''} key={key}><input type="checkbox" checked={fields.includes(key)} onChange={()=>toggle(key)}/><i>{fields.includes(key)&&<CheckCircle2/>}</i><span>{label}</span></label>)}</div>{error&&<div className="alert">{error}</div>}</div><div className="dialog-footer exportfooter"><span>{fields.length} of {all.length} columns selected</span><div><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy||!fields.length} onClick={run}><Download size={17}/>{busy?'Preparing…':'Download Excel'}</button></div></div></div></div>,document.body)
}

function Details({item,user,close,saved,refreshed,initialEditing=false}){
  const isGoogle=item.source==='google-sheet',canEdit=user.role==='admin'||(!isGoogle&&user.role==='user');
  const initiallyAssigned=(item.assignedStaff||[]).some(person=>String(person._id)===String(user.id));
  const [editing,setEditing]=useState(initialEditing),[busy,setBusy]=useState(false),[error,setError]=useState(''),[staff,setStaff]=useState([]),[selfAssigned,setSelfAssigned]=useState(initiallyAssigned);
  const seconds=interviewTimeSeconds(item.interviewTime);
  const initialForm={interviewDate:item.interviewDate&&!Number.isNaN(new Date(item.interviewDate).getTime())?new Date(item.interviewDate).toISOString().slice(0,10):'',interviewTime:Number.isFinite(seconds)?`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds/60)%60).padStart(2,'0')}`:'',technology:item.technology||'',companyName:item.companyName||'',hrName:item.hrName||'',hrEmail:item.hrEmail||'',hrMobile:item.hrMobile||'',interviewRound:item.rounds?.[0]||'',status:item.status||'Scheduled',selectedCompanyName:item.selectedCompanyName||'',remarks:item.remarks||'',assignedStaff:(item.assignedStaff||[]).map(person=>person._id)};
  const [form,setForm]=useState(initialForm);
  useEffect(()=>{if(user.role==='admin')api('/admin/users?internal=true').then(users=>setStaff(users.filter(person=>person.role==='staff'&&person.active))).catch(e=>setError(e.message))},[user.role]);
  const set=(key,value)=>setForm(current=>({...current,[key]:value}));
  async function save(){
    setBusy(true);setError('');
    try{
      const changes=interviewChanges(form,initialForm,isGoogle);
      if(!Object.keys(changes).length){setEditing(false);return}
      await api(isGoogle?`/google-sheet/${item.sheetRow}`:'/interviews/'+item._id,{method:isGoogle?'PATCH':'PUT',body:JSON.stringify(isGoogle?{changes,revision:item.revision}:changes)});
      saved();
    }catch(e){setError(e.message)}finally{setBusy(false)}
  }
  async function saveGoogleAssignment(){setBusy(true);setError('');try{await api(`/google-sheet/${item.sheetRow}/assignment`,{method:'PATCH',body:JSON.stringify({assignedStaff:form.assignedStaff})});setNoticeAndRefresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
  function setNoticeAndRefresh(){refreshed();close()}
  async function updateOwnSupport(assigned){const previous=selfAssigned;setSelfAssigned(assigned);setBusy(true);setError('');try{const path=isGoogle?`/google-sheet/${item.sheetRow}/assignment`:`/interviews/${item._id}/staff-self`;await api(path,{method:'PATCH',body:JSON.stringify({assigned})});refreshed();}catch(e){setSelfAssigned(previous);setError(e.message)}finally{setBusy(false)}}
  const toggleGoogleStaff=id=>set('assignedStaff',form.assignedStaff.includes(id)?form.assignedStaff.filter(x=>x!==id):[...form.assignedStaff,id]);
  const rows=[['Candidate name',item.candidateName],['Candidate email',item.candidateEmail],['Candidate mobile',item.candidateMobile],['Interview date',new Date(item.interviewDate).toLocaleDateString('en-IN')],['Interview time',item.interviewTime],['Technology',item.technology],['Company',item.companyName],['HR name',item.hrName],['HR email',item.hrEmail],['HR mobile',item.hrMobile],['Interview round',item.rounds?.[0]||'—'],['Support staff',item.assignedStaff?.map(person=>person.name).join(', ')||'Not assigned'],['Status',item.status],['Selected company',item.selectedCompanyName||'—'],['Remarks',item.remarks||'—']];
  return createPortal(<div className="modalback"><div className="modal detailmodal dialog-shell"><div className="dialog-header"><div><span className="eyebrow">{editing?'EDIT INTERVIEW':'COMPLETE RESPONSE'}</span><h2>{item.candidateName}</h2><p>{editing?'Update interview details and fill in missing HR contacts.':'Interview and HR contact information'}</p></div><button className="modalclose" onClick={close} aria-label="Close dialog"><X/></button></div><div className="dialog-body">{error&&<div className="alert">{error}</div>}{user.role==='staff'&&user.permissions?.selfAssign!==false&&<label className={`self-support ${selfAssigned?'selected':''}`}><input type="checkbox" checked={selfAssigned} disabled={busy} onChange={event=>updateOwnSupport(event.target.checked)}/><i>{selfAssigned&&<CheckCircle2/>}</i><span><strong>I supported this interview</strong><small>{busy?'Updating your assignment…':'This assignment is saved only in the application.'}</small></span></label>}{editing?<EditFields form={form} set={set} staff={staff} admin={user.role==='admin'&&!isGoogle}/>:<><div className="detailgrid">{rows.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>{isGoogle&&user.role==='admin'&&<div className="full"><span className="fieldlabel">Assign support staff (saved in application)</span><div className="staffchecks">{staff.map(person=><label className={form.assignedStaff.includes(person._id)?'selected':''} key={person._id}><input type="checkbox" checked={form.assignedStaff.includes(person._id)} onChange={()=>toggleGoogleStaff(person._id)}/><i>{form.assignedStaff.includes(person._id)&&<CheckCircle2/>}</i><span><strong>{person.name}</strong><small>{person.email}</small></span></label>)}</div></div>}</>}</div><div className="dialog-footer"><span>{isGoogle?(editing?'Changes are saved to the linked Google response sheet.':'Support assignments are saved in the application.'):user.role==='staff'?'Access is controlled by your staff permissions':editing?'Changes are recorded in the activity log':'Complete interview record'}</span><div><button className="secondary" onClick={editing?()=>setEditing(false):close}>{editing?'Cancel':'Close'}</button>{isGoogle&&user.role==='admin'&&!editing&&<button className="primary" disabled={busy} onClick={saveGoogleAssignment}><Save size={16}/>{busy?'Saving…':'Save support staff'}</button>}{canEdit&&!editing&&<button className="primary" onClick={()=>setEditing(true)}><Pencil size={16}/> Edit record</button>}{canEdit&&editing&&<button className="primary" disabled={busy} onClick={save}><Save size={16}/>{busy?'Saving…':'Save changes'}</button>}</div></div></div></div>,document.body)
}

function EditFields({form,set,staff,admin}){const toggleStaff=id=>set('assignedStaff',form.assignedStaff.includes(id)?form.assignedStaff.filter(x=>x!==id):[...form.assignedStaff,id]);return <div className="editgrid"><label>Interview date<input required type="date" min={todayISO()} value={form.interviewDate} onChange={e=>set('interviewDate',e.target.value)}/></label><label>Interview time<input type="time" value={form.interviewTime} onChange={e=>set('interviewTime',e.target.value)}/></label><label>Technology<input value={form.technology} onChange={e=>set('technology',e.target.value)}/></label><label>Interview round<input value={form.interviewRound} onChange={e=>set('interviewRound',e.target.value)}/></label><label>Company name<input value={form.companyName} onChange={e=>set('companyName',e.target.value)}/></label><label>Status<select value={form.status} onChange={e=>set('status',e.target.value)}>{statuses.map(status=><option key={status}>{status}</option>)}</select></label><label>HR name<input required pattern="[A-Za-z ]+" value={form.hrName} onChange={e=>set('hrName',nameOnly(e.target.value))}/></label><label>HR email<input type="email" value={form.hrEmail} onChange={e=>set('hrEmail',e.target.value)}/></label><label>HR mobile<input required inputMode="numeric" maxLength="10" value={form.hrMobile} onChange={e=>set('hrMobile',mobileOnly(e.target.value))}/></label><label>Selected / placed company<input value={form.selectedCompanyName} onChange={e=>set('selectedCompanyName',e.target.value)}/></label>{admin&&<div className="full"><span className="fieldlabel">Assign support staff</span><div className="staffchecks">{staff.map(person=><label className={form.assignedStaff.includes(person._id)?'selected':''} key={person._id}><input type="checkbox" checked={form.assignedStaff.includes(person._id)} onChange={()=>toggleStaff(person._id)}/><i>{form.assignedStaff.includes(person._id)&&<CheckCircle2/>}</i><span><strong>{person.name}</strong><small>{person.email}</small></span></label>)}</div></div>}<label className="full">Remarks<textarea rows="4" value={form.remarks} onChange={e=>set('remarks',e.target.value)}/></label></div>}
