import React,{useState} from 'react';
import {useAuth} from '../App';
import {api} from '../api';
import {CalendarCheck2,CheckCircle2,ShieldCheck,BarChart3,ArrowLeft,MailCheck} from 'lucide-react';

export default function Login(){
  const {setUser}=useAuth(),[mode,setMode]=useState('login'),[data,setData]=useState({name:'',email:'',password:'',phone:'',otp:'',newPassword:'',confirmPassword:''}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const update=(key,value)=>setData(current=>({...current,[key]:value}));
  async function submit(event){event.preventDefault();setBusy(true);setError('');setNotice('');try{if(mode==='forgot'){const result=await api('/auth/forgot-password',{method:'POST',body:JSON.stringify({email:data.email})});setNotice(result.message);setMode('reset');return}if(mode==='reset'){if(data.newPassword!==data.confirmPassword)throw new Error('New password and confirmation do not match');const result=await api('/auth/reset-password',{method:'POST',body:JSON.stringify({email:data.email,otp:data.otp,newPassword:data.newPassword,confirmPassword:data.confirmPassword})});setNotice(result.message);setMode('login');setData(current=>({...current,password:'',otp:'',newPassword:'',confirmPassword:''}));return}const result=await api(mode==='register'?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify(data)});localStorage.setItem('token',result.token);setUser(result.user)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const titles={login:['WELCOME BACK','Sign in to your workspace','Enter your email and password to continue.'],register:['CANDIDATE REGISTRATION','Create candidate account','Enter your details once. They will be reused in every interview form.'],forgot:['PASSWORD RECOVERY','Forgot your password?','Enter your registered candidate or staff email to receive a verification code.'],reset:['VERIFY YOUR EMAIL','Create a new password','Enter the six-digit OTP sent to your registered email.']},copy=titles[mode];
  return <div className="auth"><section className="auth-art"><div className="auth-copy"><div className="logo-light"><CalendarCheck2/> SmartHire</div><h1>Every interview.<br/><em>Perfectly organized.</em></h1><p>Register once, schedule interviews faster, and keep your complete interview history in one secure place.</p><div className="auth-points"><span><CheckCircle2/>Profile-based forms</span><span><ShieldCheck/>Secure candidate access</span><span><BarChart3/>Personal interview history</span></div></div><div className="orb one"/><div className="orb two"/></section><section className="auth-form"><form onSubmit={submit}><div className="mobile-logo"><CalendarCheck2/> SmartHire</div>{['forgot','reset'].includes(mode)&&<button type="button" className="auth-back" onClick={()=>{setMode('login');setError('');setNotice('')}}><ArrowLeft/> Back to sign in</button>}<span className="eyebrow">{copy[0]}</span><h2>{copy[1]}</h2><p>{copy[2]}</p>{error&&<div className="alert">{error}</div>}{notice&&<div className="success-alert"><MailCheck size={17}/>{notice}</div>}{mode==='register'&&<><label>Candidate name<input required value={data.name} onChange={e=>update('name',e.target.value)} placeholder="Your full name"/></label><label>Candidate mobile number<input required value={data.phone} onChange={e=>update('phone',e.target.value)} placeholder="+91 98765 43210"/></label></>}<label>Registered email address<input required type="email" value={data.email} onChange={e=>update('email',e.target.value)} placeholder="you@example.com"/></label>{['login','register'].includes(mode)&&<label>Password<input required minLength="8" type="password" value={data.password} onChange={e=>update('password',e.target.value)} placeholder="Minimum 8 characters"/></label>}{mode==='reset'&&<><label>Verification code<input required inputMode="numeric" maxLength="6" value={data.otp} onChange={e=>update('otp',e.target.value.replace(/\D/g,''))} placeholder="6-digit OTP"/></label><label>New password<input required minLength="8" type="password" value={data.newPassword} onChange={e=>update('newPassword',e.target.value)}/></label><label>Confirm new password<input required minLength="8" type="password" value={data.confirmPassword} onChange={e=>update('confirmPassword',e.target.value)}/></label></>}<button className="primary wide" disabled={busy}>{busy?'Please wait…':mode==='register'?'Register & continue':mode==='forgot'?'Send verification code':mode==='reset'?'Reset password':'Sign in'}</button>{mode==='login'&&<button type="button" className="forgot-link" onClick={()=>{setMode('forgot');setError('');setNotice('')}}>Forgot password?</button>}{['login','register'].includes(mode)&&<div className="switch">{mode==='register'?'Already registered?':'New candidate?'} <button type="button" onClick={()=>{setMode(mode==='register'?'login':'register');setError('');setNotice('')}}>{mode==='register'?'Sign in':'Register now'}</button></div>}</form></section></div>
}
