import React,{useEffect,useMemo,useState} from 'react';
import {UsersRound,CalendarCheck2,BriefcaseBusiness,TrendingUp,UserCog,Target,CalendarRange,UserX,Building2,Code2,Activity,AlertTriangle,ArrowUpRight} from 'lucide-react';
import {api} from '../api';
import {getDateRange,rangeOptions} from '../dateRanges';
import InterviewCalendar from './InterviewCalendar';

const colors=['#7658e8','#38afd2','#f0a83d','#39b978','#ec6b83','#9b79ef','#6477e7','#48c6a2'];

export default function AdminAnalytics(){
  const [period,setPeriod]=useState('all'),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{const params=new URLSearchParams(Object.entries(getDateRange(period)).filter(([,v])=>v));setLoading(true);Promise.all([api('/admin/analytics?'+params),api('/google-sheet/normalized?'+params)]).then(([database,sheet])=>setData(mergeSheetAnalytics(database,sheet.items))).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[period]);
  if(error)return <div className="alert">{error}</div>;
  const k=data?.kpis||{};
  const cards=[['Total interviews',k.total,BriefcaseBusiness,'violet'],["Today's interviews",k.today,CalendarCheck2,'cyan'],['Upcoming',k.upcoming,CalendarRange,'blue'],['Unassigned',k.unassigned,UserX,'pink'],['Candidates',k.registered,UsersRound,'blue'],['Active staff',k.activeStaff,UserCog,'amber'],['Selected / placed',k.selected,Target,'green'],['Selection rate',`${k.conversion||0}%`,TrendingUp,'pink']];
  return <div className={loading?'bi-dashboard bi-loading':'bi-dashboard'}>
    <section className="bi-title"><div><span className="eyebrow">ADMIN INTELLIGENCE</span><h1>Interview analytics</h1><p>Live operational insights across candidates, domains and staff.</p></div><div className="quickranges compactranges">{rangeOptions.map(([key,label])=><button key={key} className={period===key?'active':''} onClick={()=>setPeriod(key)}>{label}</button>)}</div></section>
    <section className="bi-kpis executive-kpis">{cards.map(([label,value,Icon,tone])=><article className={`bi-kpi ${tone}`} key={label}><div><span>{label}</span><strong>{value??'—'}</strong></div><i><Icon/></i></article>)}</section>
    <section className="executive-calendar"><ExecutiveSummary data={data}/><InterviewCalendar role="admin"/></section>
    <section className="bi-grid">
      <ChartCard title="Interview trend" subtitle="Interviews by day" wide><TrendChart data={data?.trend||[]}/></ChartCard>
      <ChartCard title="Status distribution" subtitle="Current pipeline health"><DonutChart data={data?.status||[]}/></ChartCard>
      <ChartCard title="Technology-wise interviews" subtitle="Count and percentage of total interviews"><TechnologyMix data={data?.technology||[]} total={k.total||0}/></ChartCard>
      <ChartCard title="Top companies" subtitle="Companies by interview volume"><CompanyBars data={data?.company||[]}/></ChartCard>
      <ChartCard title="Staff utilization today" subtitle="Assigned candidate support"><StaffBars data={data?.staffWorkload||[]}/></ChartCard>
      <ChartCard title={`Today's schedule (${data?.today?.length||0})`} subtitle="Candidate, domain and support staff" wide><TodayTable items={data?.today||[]}/></ChartCard>
    </section>
  </div>
}

function mergeGroups(primary,items,key,limit=10){const counts=new Map(primary.map(item=>[item._id,item.count]));items.forEach(item=>{const value=item[key]||'Unknown';counts.set(value,(counts.get(value)||0)+1)});return [...counts].map(([_id,count])=>({_id,count})).sort((a,b)=>b.count-a.count).slice(0,limit)}
function mergeSheetAnalytics(database,items){const todayStart=new Date();todayStart.setHours(0,0,0,0);const todayEnd=new Date(todayStart);todayEnd.setHours(23,59,59,999);const today=items.filter(item=>{const date=new Date(item.interviewDate);return date>=todayStart&&date<=todayEnd}),sheetSelected=items.filter(item=>['Selected','Placed'].includes(item.status)).length,total=(database.kpis.total||0)+items.length;const trendCounts=new Map((database.trend||[]).map(item=>[item._id,item.count]));items.forEach(item=>{if(item.interviewDate){const day=String(item.interviewDate).slice(0,10);trendCounts.set(day,(trendCounts.get(day)||0)+1)}});const technology=mergeGroups(database.technology||[],items,'technology'),company=mergeGroups(database.company||[],items,'companyName'),status=mergeGroups(database.status||[],items,'status');return {...database,technology,company,status,trend:[...trendCounts].map(([_id,count])=>({_id,count})).sort((a,b)=>a._id.localeCompare(b._id)),today:[...(database.today||[]),...today].sort((a,b)=>String(a.interviewTime).localeCompare(String(b.interviewTime))),kpis:{...database.kpis,total,today:(database.kpis.today||0)+today.length,upcoming:(database.kpis.upcoming||0)+items.filter(item=>new Date(item.interviewDate)>todayEnd).length,unassigned:(database.kpis.unassigned||0)+items.length,selected:(database.kpis.selected||0)+sheetSelected,placed:(database.kpis.placed||0)+items.filter(item=>item.status==='Placed').length,rejected:(database.kpis.rejected||0)+items.filter(item=>item.status==='Rejected').length,conversion:total?Math.round(((database.kpis.selected||0)+sheetSelected)/total*100):0},insights:{...database.insights,busiestTechnology:technology[0]?{name:technology[0]._id,count:technology[0].count}:null,busiestCompany:company[0]?{name:company[0]._id,count:company[0].count}:null,averagePerCandidate:database.kpis.registered?Number((total/database.kpis.registered).toFixed(1)):0}}}

function ExecutiveSummary({data}){const k=data?.kpis||{},insights=data?.insights||{};const alerts=[k.unassigned?`${k.unassigned} interviews need staff assignment`:'All interviews have staff coverage',k.today?`${k.today} interviews scheduled today`:'No interviews scheduled today',k.upcoming?`${k.upcoming} upcoming interviews in the pipeline`:'No future interviews scheduled'];return <section className="executive-row"><article className="insight-card"><header><Activity/><div><strong>Executive summary</strong><small>Automatically generated from live records</small></div></header><div className="insight-metrics"><div><Code2/><span>Top domain</span><strong>{insights.busiestTechnology?.name||'No data'}</strong><small>{insights.busiestTechnology?.count||0} interviews</small></div><div><Building2/><span>Top company</span><strong>{insights.busiestCompany?.name||'No data'}</strong><small>{insights.busiestCompany?.count||0} interviews</small></div><div><UsersRound/><span>Avg. per candidate</span><strong>{insights.averagePerCandidate||0}</strong><small>interviews each</small></div></div></article><article className="attention-card"><header><AlertTriangle/><div><strong>Management attention</strong><small>Items requiring awareness</small></div></header>{alerts.map((text,index)=><div className={index===0&&k.unassigned?'warning':'okay'} key={text}><i/><span>{text}</span><ArrowUpRight/></div>)}</article></section>}

function ChartCard({title,subtitle,wide,children}){return <article className={wide?'bi-card wide':'bi-card'}><header><div><h3>{title}</h3><p>{subtitle}</p></div><span className="live-dot">Live</span></header><div className="bi-chart">{children}</div></article>}
function HorizontalBars({data}){const max=Math.max(...data.map(x=>x.count),1);return <div className="hbars">{data.length?data.map((item,index)=><div key={item._id||'Unknown'}><div><span>{item._id||'Unknown'}</span><strong>{item.count}</strong></div><i><b style={{width:`${item.count/max*100}%`,background:colors[index%colors.length]}}/></i></div>):<Empty/>}</div>}
function TechnologyMix({data,total}){let cursor=0;const segments=data.map((item,index)=>{const percentage=total?item.count/total*100:0,start=cursor;cursor+=percentage;return {...item,percentage,start,end:cursor,color:colors[index%colors.length]}});return data.length?<div className="techmix"><div className="techsummary"><div className="techdonut" style={{background:`conic-gradient(${segments.map(item=>`${item.color} ${item.start}% ${item.end}%`).join(',')})`}}><div><strong>{total}</strong><span>Total interviews</span><small>{data.length} technologies</small></div></div></div><div className="techlist">{segments.map(item=><div key={item._id||'Unknown'}><i style={{background:item.color}}/><div><strong>{item._id||'Unknown'}</strong><span><b style={{width:`${item.percentage}%`,background:item.color}}/></span></div><em>{item.count}<small>{Math.round(item.percentage)}%</small></em></div>)}</div></div>:<Empty/>}
function CompanyBars({data}){const max=Math.max(...data.map(x=>x.count),1);return <div className="companybars">{data.length?data.slice(0,6).map((item,index)=><div key={item._id||'Unknown'}><span title={item._id}>{item._id||'Unknown'}</span><i><b style={{height:`${Math.max(10,item.count/max*100)}%`,background:colors[index%colors.length]}}/></i><strong>{item.count}</strong></div>):<Empty/>}</div>}
function DonutChart({data}){const total=data.reduce((sum,x)=>sum+x.count,0),segments=[];let cursor=0;data.forEach((item,index)=>{const start=cursor,c=item.count/(total||1)*100;cursor+=c;segments.push(`${colors[index%colors.length]} ${start}% ${cursor}%`)});return data.length?<div className="donutwrap"><div className="donut" style={{background:`conic-gradient(${segments.join(',')})`}}><div><strong>{total}</strong><span>Total</span></div></div><div className="legend">{data.map((item,index)=><div key={item._id}><i style={{background:colors[index%colors.length]}}/><span>{item._id}</span><strong>{item.count}</strong></div>)}</div></div>:<Empty/>}
function TrendChart({data}){const [active,setActive]=useState(null),points=useMemo(()=>{const max=Math.max(...data.map(x=>x.count),1);return data.map((item,index)=>({x:data.length===1?50:index/(data.length-1)*100,y:88-item.count/max*72,...item}))},[data]);const move=event=>{const box=event.currentTarget.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientX-box.left)/box.width)),index=Math.round(ratio*(points.length-1));setActive(points[index])};const dateLabel=value=>new Date(value+'T00:00:00').toLocaleDateString('en-IN',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});return data.length?<div className="trend interactive-trend" onMouseLeave={()=>setActive(null)}><svg viewBox="0 0 100 100" preserveAspectRatio="none" onMouseMove={move}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7658e8" stopOpacity=".34"/><stop offset="1" stopColor="#7658e8" stopOpacity="0"/></linearGradient></defs><path className="area" d={`M ${points[0].x} 92 L ${points.map(p=>`${p.x} ${p.y}`).join(' L ')} L ${points.at(-1).x} 92 Z`}/><polyline points={points.map(p=>`${p.x},${p.y}`).join(' ')} />{active&&<><line className="trend-guide" x1={active.x} y1="4" x2={active.x} y2="92"/><circle className="trend-point-halo" cx={active.x} cy={active.y} r="2.2"/><circle className="trend-point" cx={active.x} cy={active.y} r="1.15"/></>}</svg>{active&&<div className={`trend-tooltip ${active.x>78?'align-right':''}`} style={{left:`${active.x}%`,top:`${Math.max(2,active.y-9)}%`}}><span>{dateLabel(active._id)}</span><strong>{active.count} {active.count===1?'interview':'interviews'}</strong></div>}<div className="trendlabels">{data.filter((_,i)=>i===0||i===data.length-1||i===Math.floor(data.length/2)).map(x=><span key={x._id}>{new Date(x._id+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</span>)}</div></div>:<Empty/>}
function TodayTable({items}){return items.length?<div className="todaylist">{items.map(item=><article key={item._id}><time>{item.interviewTime}</time><div className="candidate"><strong>{item.candidateName}</strong><small>{item.companyName}</small></div><span className="domain">{item.technology}</span><div className="support"><small>Supported by</small><strong>{item.assignedStaff?.map(x=>x.name).join(', ')||'Unassigned'}</strong></div><span className={`status ${item.status.toLowerCase().replace(' ','-')}`}>{item.status}</span></article>)}</div>:<Empty text="No interviews scheduled today"/>}
function Empty({text='No data for this period'}){return <div className="bi-empty">{text}</div>}
function StaffBars({data}){const max=Math.max(...data.map(x=>x.count),1);return <div className="staffbars">{data.length?data.map(member=><div key={member._id}><div className="avatar soft">{member.name.slice(0,2).toUpperCase()}</div><div><strong>{member.name}</strong><small>{member.candidates?.join(', ')||'No candidates today'}</small><i><b style={{width:`${member.count/max*100}%`}}/></i></div><span>{member.count}</span></div>):<Empty text="No active staff"/>}</div>}
